postgresql:
  image: orchardup/postgresql:latest
  environment:
    - POSTGRESQL_USER=xxx
    - POSTGRESQL_PASS=xxx
    - POSTGRESQL_DB=xxx
  volumes:
    - /opt/db/sonarqube/:/var/lib/postgresql
  ports:
    - "5050:5432"
sonarqube:
  image: sonarqube:latest
  links:
    - postgresql:db
  environment:
    - DB_USER=xxx
    - DB_PASS=xxx
    - DB_NAME=xxx
  ports:
    - "9000:9000"
    - "443"
